// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package handlers

// Submit defines model for Submit.
type Submit struct {
	Statement string `json:"statement"`
	TaskId    string `json:"task_id"`
}

// SubmitJSONRequestBody defines body for Submit for application/json ContentType.
type SubmitJSONRequestBody = Submit
